#!/bin/bash 

if [ "$#" -eq 1 ]; then
	fullfile=$(basename "$1")
	diffflag=0
elif [ "$#" -eq 2 ]; then
	fullfile=$(basename "$2")
	diffflag=1
elif [ "$#" -eq 3 ]; then
	oldfile=$(basename "$2")
	fullfile=$(basename "$3")
	diffflag=2
else 
	echo "Not supported"
fi

filename="${fullfile%.*}"
extension="${fullfile##*.}"



latexmk -pdf -output-directory=.compfiles $fullfile; cp .compfiles/${filename}.pdf ${filename}.pdf 

if [ $diffflag -eq 1 ]; then
	git show HEAD:$fullfile > .compfiles/previous.tex
	latexdiff .compfiles/previous.tex $fullfile > diff.tex
	latexmk -pdf -output-directory=.compfiles diff.tex; cp .compfiles/diff.pdf diff.pdf
	rm diff.tex
elif [ $diffflag -eq 2 ]; then
	latexdiff $oldfile $fullfile > diff.tex
	latexmk -pdf -output-directory=.compfiles diff.tex; cp .compfiles/diff.pdf diff.pdf
	rm diff.tex
fi
